#!/usr/bin/env bash
# start.sh - simple one-command bootstrap for ISeeYou (dev-friendly)
# This script will:
# 1. Generate a secure random ISEEYOU_SECRET if none exists
# 2. Generate a bcrypt hashed admin password (default: 'iseeyou' - change later!)
# 3. Write a .env file consumed by docker-compose
# 4. Run `docker-compose up --build -d

# Usage: ./start.sh
set -euo pipefail

# Default admin password (change after first run!)
ADMIN_PASS="${ADMIN_PASS:-iseeyou}"
REDIS_URL="${REDIS_URL:-redis://redis:6379/0}"

if [ -f .env ]; then
  echo ".env already exists. If you want a fresh install remove .env first."
else
  echo "Generating .env..."
  ISEEYOU_SECRET="$(python3 - <<'PY'
import secrets,sys
print(secrets.token_urlsafe(32))
PY
)"
  # generate bcrypt hash using python from virtual environment
  ADMIN_PASS_HASH="$(source venv/bin/activate && python3 - <<'PY'
import bcrypt,os
pw = os.environ.get('ADMIN_PASS','iseeyou').encode()
print(bcrypt.hashpw(pw, bcrypt.gensalt()).decode())
PY
)"
  cat > .env <<EOF
# Auto-generated by start.sh - override values before running if desired
ENV=production
ISEEYOU_SECRET=$ISEEYOU_SECRET
ISEEYOU_ADMIN_PASS_HASH=$ADMIN_PASS_HASH
REDIS_URL=$REDIS_URL
EOF
  echo ".env written (inspect & secure it)."
fi

# Try to start with docker-compose
if command -v docker >/dev/null 2>&1 && command -v docker-compose >/dev/null 2>&1; then
  echo "Starting docker-compose..."
  docker-compose up --build -d

  # After starting, verify that optional Python packages are present in the container
  echo "Verifying installed optional packages inside container..."
  echo "Checking for prometheus_client and Flask-Talisman inside the container..."
  
  # Wait a moment for the container to be fully ready
  sleep 2
  
  # Check prometheus_client
  if docker exec iseeyou_iseeyou_1 python -c "import prometheus_client; print('prometheus_client: OK')" 2>/dev/null; then
    echo "prometheus_client: OK"
  else
    echo "prometheus_client: MISSING"
  fi
  
  # Check flask_talisman
  if docker exec iseeyou_iseeyou_1 python -c "import flask_talisman; print('Flask-Talisman: OK')" 2>/dev/null; then
    echo "Flask-Talisman: OK"
  else
    echo "Flask-Talisman: MISSING"
  fi
  
  echo "Optional packages verification complete. Metrics and Talisman should be available."

  echo "Services started. Check logs with: docker-compose logs -f"
  echo "Visit http://localhost:8000 (or configure your reverse proxy)."
else
  echo "Docker or docker-compose not found. Please install Docker and docker-compose, or run the server manually:"
  echo "  python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt"
  echo "  export ISEEYOU_SECRET=your_secret_here"
  echo "  export ISEEYOU_ADMIN_PASS_HASH=the_hash_here"
  echo "  python3 iseeyou_server.py"
fi

# Print quick status from .env (if exists)
if [ -f .env ]; then
  echo "Configuration (.env):"
  grep -E '^(ENV|REDIS_URL|ISEEYOU_ADMIN_PASS_HASH)' .env || true
fi
