#!/usr/bin/env bash
# start.sh - secure one-command bootstrap for ISeeYou
# This script will:
# 1. Generate a secure random ISEEYOU_SECRET if none exists
# 2. Generate a bcrypt hashed admin password (default: 'iseeyou' - change later!)
# 3. Generate a secure Redis password
# 4. Write a secure .env file consumed by docker-compose
# 5. Run `docker-compose up --build -d

# After starting, verify that optional Python packages are present in the container
echo "Verifying installed optional packages inside container..."
if command -v docker >/dev/null 2>&1 && command -v docker-compose >/dev/null 2>&1; then
  echo "Checking for Flask-SeaSurf, prometheus_client, and Flask-Talisman inside the container..."
  docker-compose run --rm iseeyou python - <<'PY'
import sys
ok = True
try:
    import flask_seasurf
    print("Flask-SeaSurf: OK")
except Exception as e:
    ok = False
    print("Flask-SeaSurf: MISSING -", e)
try:
    import prometheus_client
    print("prometheus_client: OK")
except Exception as e:
    ok = False
    print("prometheus_client: MISSING -", e)
try:
    import flask_talisman
    print("Flask-Talisman: OK")
except Exception as e:
    ok = False
    print("Flask-Talisman: MISSING -", e)
sys.exit(0 if ok else 1)
PY
  if [ $? -eq 0 ]; then
    echo "Optional packages are present. CSRF, metrics, and Talisman should be available."
  else
    echo "Some optional packages are missing inside the image. See output above to install them or rebuild the image."
  fi
fi
` to start services (requires Docker & docker-compose)
#
# Usage: ./start.sh
set -euo pipefail

# Default admin password (change after first run!)
ADMIN_PASS="${ADMIN_PASS:-iseeyou}"
REDIS_URL="${REDIS_URL:-redis://redis:6379/0}"

if [ -f .env ]; then
  echo ".env already exists. If you want a fresh install remove .env first."
else
  echo "Generating secure .env configuration..."
  ISEEYOU_SECRET="$(python3 - <<'PY'
import secrets,sys
print(secrets.token_urlsafe(32))
PY
)"
  # generate bcrypt hash using python
  ADMIN_PASS_HASH="$(python3 - <<'PY'
import bcrypt,os
pw = os.environ.get('ADMIN_PASS','iseeyou').encode()
print(bcrypt.hashpw(pw, bcrypt.gensalt()).decode())
PY
)"
  # generate secure Redis password
  REDIS_PASSWORD="$(python3 - <<'PY'
import secrets,sys
print(secrets.token_urlsafe(16))
PY
)"

  cat > .env <<EOF
# Auto-generated by start.sh - override values before running if desired
# SECURITY WARNING: Change the default admin password immediately after first login!
ENV=production
ISEEYOU_SECRET=$ISEEYOU_SECRET
ISEEYOU_ADMIN_PASS_HASH=$ADMIN_PASS_HASH
REDIS_URL=$REDIS_URL
REDIS_PASSWORD=$REDIS_PASSWORD

# Application Configuration
PYTHONUNBUFFERED=1
PYTHONPATH=/app
EOF
  echo ".env written with secure defaults (inspect & secure it)."
  echo "SECURITY NOTICE: Default admin password is 'iseeyou' - change it immediately!"
fi

# Try to start with docker-compose
if command -v docker >/dev/null 2>&1 && command -v docker-compose >/dev/null 2>&1; then
  echo "Starting docker-compose..."
  docker-compose up --build -d

# After starting, verify that optional Python packages are present in the container
echo "Verifying installed optional packages inside container..."
if command -v docker >/dev/null 2>&1 && command -v docker-compose >/dev/null 2>&1; then
  echo "Checking for Flask-SeaSurf, prometheus_client, and Flask-Talisman inside the container..."
  docker-compose run --rm iseeyou python - <<'PY'
import sys
ok = True
try:
    import flask_seasurf
    print("Flask-SeaSurf: OK")
except Exception as e:
    ok = False
    print("Flask-SeaSurf: MISSING -", e)
try:
    import prometheus_client
    print("prometheus_client: OK")
except Exception as e:
    ok = False
    print("prometheus_client: MISSING -", e)
try:
    import flask_talisman
    print("Flask-Talisman: OK")
except Exception as e:
    ok = False
    print("Flask-Talisman: MISSING -", e)
sys.exit(0 if ok else 1)
PY
  if [ $? -eq 0 ]; then
    echo "Optional packages are present. CSRF, metrics, and Talisman should be available."
  else
    echo "Some optional packages are missing inside the image. See output above to install them or rebuild the image."
  fi
fi

  echo "Services started. Check logs with: docker-compose logs -f"
  echo "Visit http://localhost:8000 (or configure your reverse proxy)."
else
  echo "Docker or docker-compose not found. Please install Docker and docker-compose, or run the server manually:"
  echo "  python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt"
  echo "  export ISEEYOU_SECRET=your_secret_here"
  echo "  export ISEEYOU_ADMIN_PASS_HASH=the_hash_here"
  echo "  python3 iseeyou_server.py"
fi


# Print quick status from .env (if exists)
if [ -f .env ]; then
  echo "Configuration (.env):"
  grep -E '^(ENV|REDIS_URL|ISEEYOU_ADMIN_PASS_HASH)' .env || true
fi
